# Generated by Django 3.0.5 on 2020-05-02 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='', upload_to='images/photos')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('like_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='images.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
