# Generated by Django 3.0.5 on 2020-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
