# Generated by Django 3.0.5 on 2020-05-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('persons', '0004_auto_20200502_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(default='', upload_to='persons/photos/profile_images')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
    ]
