# Generated by Django 3.0.5 on 2020-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_pic', upload_to='persons/photos/profile_images'),
        ),
    ]
