# Generated by Django 3.0.7 on 2020-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20200503_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='persons/profile_images/default_pic.png', upload_to='persons/profile_images'),
        ),
    ]
